// Generated by CoffeeScript 1.6.3
(function() {
  var animate_sprite;

  $(function() {
    return $('.button').hover(function() {
      return animate_sprite(this, 100, '100%');
    }, function() {
      return animate_sprite(this, 100, '0%');
    });
  });

  animate_sprite = function(obj, delay, pos) {
    return $(obj).fadeToggle(delay, function() {
      return $(obj).animate({
        'background-position-x': pos
      }, 0, function() {
        return $(obj).fadeToggle(delay);
      });
    });
  };

}).call(this);
