// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('article').each(function(index) {
      if (index % 2 === 1) {
        return $(this).addClass('zebra_1 vertical_shadow');
      }
    });
  });

}).call(this);
